### PR TITLE
Added Checks for downloading tool's & wordlist

### PR DESCRIPTION
**Pull request by noob6t5**
In this PR , 
I have added download Check's which let user checking every tool, wordlist,resolver.

If those aren't installed in `anveshan`  then it install's .

```
But if they are already present there , It stops downloading again saving time , storage, and making code better . Since , Earlier you mentioned tool can be installed anywhere so i  have only added function for  `anveshan` directory.

User can run tool many times , but downloading already downloaded stuff's is irritating and takes time too..
``` 

Please do review..
**Below you can see tool is installed twice , everytime i run ./setup-sh those will be installed** 
 Before::::::::
doubleinst

  Checking:::::::::;

check

### CODE REVIEW

**Comment by hackersthan** [comment]
Hello @noob6t5

You did a great work, but if tools, such as `subdominator` `knock` `urless` etc, are already installed than pip will throw a error and says package are already installed so no need of `installation checks` for packages in `pip` `apt` and `go`.

Second `setup_linux.sh` file should run once and if user tries to rerun it wordlists and config file are just overright so there is no need to check for these file too.
We should update our resolvers time to time using dnsvalidator.

Still i will do some more research on it and let you know if it was a issue to fix.

Thanks again to making `anveshan` better.
Sachin

**Comment by noob6t5** [comment]
Sure. 
 & I'm sorry bro I didn't thought about resolvers.
Please let me know what we can do for this

**Comment by hackersthan** [comment]
Today i will merge after some changes.

**Comment by hackersthan** [comment]
Also i have another idea, I will add another function that fetch new resolvers if they are older than 3 days with user permission obviously.

**Comment by noob6t5** [comment]
sure bro 🔥🔥🔥

**Comment by hackersthan** [comment]
Hello @noob6t5 

I fixed all of these things and also added a logs feature that helps to check errors. Checkout 2b46faf6708d86c158670cc9c31715fa4272ddda and if you found any errors please let me know.

Thanks for your suggestions.

**Comment by hackersthan** [comment]
In next update i will add fresh resolvers feature and i will use `grep -m 1 'current_version'` instead of `grep -m 1 'current_version\='` so it will fetch current feature from first match line.

**Comment by noob6t5** [comment]
okay bro , I will roam more in holiday's ...I also got some more idea's I will make another PR  for it , 
Let's close this PR

**Comment by hackersthan** [comment]
Okay, i hope you got this. Defiantly work on your ideas.

**Pull request closed without merging**
