### PR TITLE
Options Added for other editor's nano ,vim & gedit

### PR DESCRIPTION
**Pull request by noob6t5**
Hello Again!!,
As previous pip update worked fine , I am checking it ...

**Right now this tool install's everything from scratch , But it should also check for previously installed tool , so it doesn't conflict's between tool's. So , let's work in this too.**

In this PR , 
```
1.  I have updated the code so that  Config file can be opened with nano vim or gedit ..
2. Updated checks so that chrome(.deb) isn't installed double  and  cleans  file....
```

Before:
only_notepad

doubleinst

### CODE REVIEW

**Review by hackersthan — CHANGES_REQUESTED** [review]
looks fine but these file must open in GUI based editor so lets put like this
1. notepad
2. gedit
3. nano [if both are not available]

```
if [[ "$apianswer" == [Yy] ]]; then
        if command -v notepad &> /dev/null; then
        editor="notepad"
    elif command -v gedit &> /dev/null; then
        editor="gedit"
    elif command -v nano &> /dev/null; then
        editor="nano"
    else
        printf "${red}No  text editor found. Please open these api config files manually${reset}\n"
        exit 1
    fi
```

**Review by hackersthan — APPROVED** [review]

**Comment by hackersthan** [comment]
Check yourself too, then we can merge this.

**Review by hackersthan — APPROVED** [review]

**Comment by noob6t5** [comment]
yes, it's working..

working



Now , We should add code that check's if tool is previously installed or not . So it avoid's flooding terminal and creating conflicts.


Thanks Again ..

**Comment by hackersthan** [comment]
I updates some more. For paramspider, anveshan use https://github.com/0xKayala/ParamSpider and not the https://github.com/devanshbatham/ParamSpider, so i have to install it in anveshan directory then directly access from here. so if user have already another paramspider it did not mix with that.

**Comment by hackersthan** [comment]
Hello @noob6t5 

First of all thanks for your support to project `anveshan`.

I think everything is fine now,
No need to check already installed tools for pip, apt, and go.
Paramspider and shrewdeye-bash downloads in `$HOME/anveshan` directory and access from here.
Wordlists and config file are downloads in `$HOME/anveshan` directory and $HOME/anveshan

If you have any recommendation, you can reply here.

Thanks,
Sachin

**Comment by noob6t5** [comment]
It right now install's wordlist's ,chrome ,resolver's again. Even if it's installed , So i think we have to look into it keeping check for those

**Comment by noob6t5** [comment]
can you please my second commit too. I have added check's for chrome installation too.

**Comment by hackersthan** [comment]
I already check your google chrome code and approved it.

For wordlists and config file, they might be downloaded somewhere but not in `$HOME/anveshan` directory, so we need to download here and setup, so `anveshan` tools can access them from here.

**Comment by hackersthan** [comment]
Everything is alright now, I'm adding these to the main branch.

**Pull request merged**
